export const GET_TEACHER_QUESTIONS = "GET_TEACHER_QUESTIONS";
export const FETCH_TEACHER_QUESTIONS = "FETCH_TEACHER_QUESTIONS";
export const SET_TEACHER_QUESTIONS = "SET_TEACHER_QUESTIONS";
export const GET_IS_QUESTION_LOADING = "GET_IS_QUESTION_LOADING";
export const SET_IS_QUESTION_LOADING = "SET_IS_QUESTION_LOADING";
export const TEACHER_QUESTIONS_URL = (payload) => {
  return `/teacher/homework-questions?homework_id=${payload}`;
};
export const ASSESMENT_PUBLISH_ACTION = "ASSESMENT_PUBLISH_ACTION";

export const GET_IS_ASESSMENT_PUBLISHING = "GET_IS_ASESSMENT_PUBLISHING";

export const SET_IS_ASESSMENT_PUBLISHING = "SET_IS_ASESSMENT_PUBLISHING";

export const GET_PUBLISHED_DATA = "GET_PUBLISHED_DATA";

export const SET_PUBLISHED_DATA = "SET_PUBLISHED_DATA";

export const ASSESMENT_DELETE_ACTION = "ASSESMENT_DELETE_ACTION";

export const GET_IS_ASESSMENT_DELETING = "GET_IS_ASESSMENT_DELETING";

export const SET_IS_ASESSMENT_DELETING = "SET_IS_ASESSMENT_DELETING";

export const GET_DELETE_DATA = "GET_DELETE_DATA";

export const SET_DELETE_DATA = "SET_DELETE_DATA";

export const PUBLISH_URL = (id) => {
  return `/teacher/homework/publish/${id}`;
};

export const HOMEWORK_URL = (id) => {
  return `/teacher/homework/${id}`;
};

export const GET_ASSESMENT_DETAILS = "GET_ASSESMENT_DETAILS";

export const SET_ASSESMENT_DETAILS = "SET_ASSESMENT_DETAILS";

export const GET_ASSESMENT_DETAILS_ACTION = "GET_ASSESMENT_DETAILS_ACTION";

export const GET_IS_ASSESMENT_DETAILS_LOADING =
  "GET_IS_ASSESMENT_DETAILS_LOADING";

export const SET_IS_ASSESMENT_DETAILS_LOADING =
  "SET_IS_ASSESMENT_DETAILS_LOADING";

export const EDIT_ASSESMENT_DETAILS_ACTION = "EDIT_ASSESMENT_DETAILS_ACTION";

export const GET_EDIT_ASSESMENT_DETAILS = "GET_EDIT_ASSESMENT_DETAILS";

export const SET_EDIT_ASSESMENT_DETAILS = "SET_EDIT_ASSESMENT_DETAILS";

export const GET_IS_ASSESMENT_EDITING = "GET_IS_ASSESMENT_EDITING";

export const SET_IS_ASSESMENT_EDITING = "SET_IS_ASSESMENT_EDITING";
