const students = [
  {
    id: 1,
    firstname: "Aisha",
    lastname: "Bello",
    full_name: "Aisha Bello",
    image: require(`@/modules/base/assets/static/OnboardingChildOne.png`),
    code: "UED/2019/0856",
    is_graded: 1,
    proctor: "",
    quizSummaryScore: 0,
    score: 25,
    submit_at: "2021-09-26 18:49:57",
  },
  {
    id: 2,
    firstname: "Richy",
    lastname: "Jones",
    full_name: "Richy Jones",
    image: require(`@/modules/base/assets/static/OnboardingChildTwo.png`),
    code: "UED/2019/0857",
    is_graded: 1,
    proctor: "",
    quizSummaryScore: 0,
    score: 95,
    submit_at: "2021-09-26 18:49:57",
  },
  {
    id: 3,
    firstname: "Sandra",
    lastname: "Okoro",
    full_name: "Sandra Okoro",
    image: require(`@/modules/base/assets/static/OnboardingChildThree.png`),
    code: "UED/2019/0858",
    is_graded: 1,
    proctor: "",
    quizSummaryScore: 0,
    score: 35,
    submit_at: "2021-09-26 18:49:57",
  },
  {
    id: 4,
    firstname: "Philip",
    lastname: "Ojo",
    full_name: "Philip Ojo",
    image: require(`@/modules/base/assets/static/OnboardingChildFour.png`),
    code: "UED/2019/0859",
    is_graded: 1,
    proctor: "",
    quizSummaryScore: 0,
    score: 50,
    submit_at: "2021-09-26 18:49:57",
  },
  {
    id: 5,
    firstname: "Ngozi",
    lastname: "Okoye",
    full_name: "Ngozi Okoye",
    image: require(`@/modules/base/assets/static/OnboardingChildFive.png`),
    code: "UED/2019/0860",
    is_graded: 1,
    proctor: "",
    quizSummaryScore: 0,
    score: 80,
    submit_at: "2021-09-26 18:49:57",
  },
];

export default students;
