const questions = [
  {
    id: 1,
    question:
      "<p>Which of the pronouns in the options below ask questions about things?</p>",
    option_a: "Who",
    option_b: "Whom",
    option_c: "Which",
    option_d: "That",
    option_e: null,
    answer: "C",
    image: null,
    duration: 60,
    difficulty: "medium",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 2,
    question:
      "<p><b>Identify the interrogative pronoun in the sentence below:</b> </br> Where is the boy that came first in class?</p>",
    option_a: "Boy",
    option_b: "That",
    option_c: "First",
    option_d: "Where",
    option_e: null,
    answer: "D",
    image: null,
    duration: 30,
    difficulty: "easy",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 3,
    question:
      "<p>A pronoun that refers to non-specific people and things is known as __________?</p>",
    option_a: "Definite pronoun",
    option_b: "Relative pronoun",
    option_c: "Indefinite pronoun",
    option_d: "Demonstrative pronoun",
    option_e: null,
    answer: "C",
    image: null,
    duration: 60,
    difficulty: "hard",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 4,
    question:
      "<p><b>Complete this sentence with an appropriate pronoun:</b> </br> ___ is knocking on the door?</p>",
    option_a: "Whose",
    option_b: "What",
    option_c: "Who",
    option_d: "Where",
    option_e: null,
    answer: "C",
    image: null,
    duration: 30,
    difficulty: "easy",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 5,
    question:
      "<p><b>Complete this sentence with an appropriate pronoun:</b> </br> To ___ it may concern, I am the new class prefect.</p>",
    option_a: "Who",
    option_b: "Which",
    option_c: "Whom",
    option_d: "Whose",
    option_e: null,
    answer: "C",
    image: null,
    duration: 60,
    difficulty: "hard",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 6,
    question:
      "<p><b>Complete this sentence with an appropriate pronoun:</b> </br> The headmaster gave _____ a prize.</p>",
    option_a: "WE",
    option_b: "They",
    option_c: "I",
    option_d: "Us",
    option_e: null,
    answer: "D",
    image: null,
    duration: 60,
    difficulty: "hard",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 7,
    question:
      "<p><b>Complete this sentence with an appropriate pronoun:</b> </br> _______ is the meaning of NNPC?</p>",
    option_a: "Who",
    option_b: "Which",
    option_c: "Whose",
    option_d: "What",
    option_e: null,
    answer: "D",
    image: null,
    duration: 30,
    difficulty: "easy",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 8,
    question:
      "<p><b>Complete this sentence with an appropriate possesive pronoun:</b> </br> This shoe is for Jacob. It is ___.</p>",
    option_a: "Him",
    option_b: "Himself",
    option_c: "He's",
    option_d: "His",
    option_e: null,
    answer: "D",
    image: null,
    duration: 45,
    difficulty: "medium",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 9,
    question:
      "<p><b>Complete this sentence with an appropriate possesive pronoun:</b> </br> These books belong to us. They are ______.</p>",
    option_a: "Our",
    option_b: "Ourselves",
    option_c: "Ours",
    option_d: "Yourself",
    option_e: null,
    answer: "C",
    image: null,
    duration: 45,
    difficulty: "medium",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 10,
    question:
      "<p><b>Complete this sentence with an appropriate relative pronoun:</b> </br> Here are the boys ___ bags we saw yesterday.</p>",
    option_a: "Who",
    option_b: "Whose",
    option_c: "Whom",
    option_d: "Which",
    option_e: null,
    answer: "B",
    image: null,
    duration: 30,
    difficulty: "easy",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 11,
    question:
      "<p><b>Complete this sentence with an appropriate relative pronoun:</b> </br> At ___ expense shall we hold the party?</p>",
    option_a: "Whom",
    option_b: "Whose",
    option_c: "Which",
    option_d: "Who",
    option_e: null,
    answer: "B",
    image: null,
    duration: 60,
    difficulty: "hard",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 12,
    question:
      "<p><b>Complete this sentence with an appropriate personal pronoun:</b> </br> I love Tobi because ........ is a smart boy.</p>",
    option_a: "He",
    option_b: "I",
    option_c: "Him",
    option_d: "She",
    option_e: null,
    answer: "A",
    image: null,
    duration: 30,
    difficulty: "easy",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
  {
    id: 13,
    question:
      "<p><b>Complete this sentence with an appropriate personal pronoun:</b> </br>  ....... were not allowed to attend the meeting.</p>",
    option_a: "I and Taiwo",
    option_b: "Taiwo and I",
    option_c: "Me and Taiwo",
    option_d: "Taiwo and Me",
    option_e: null,
    answer: "B",
    image: null,
    duration: 45,
    difficulty: "medium",
    type: "multiple",
    topic_id: 1,
    explanation: "",
    video_explanation: null,
    comprehension: null,
    comprehension_id: null,
    topic: "Pronoun",
    owner: 0,
    file_upload: null,
    word_limit: null,
    correct_students: [],
    wrong_students: [],
  },
];

export default questions;
